title: Documentation for the ProKabaddi API
description: A comprehensive description of all the endpoints for the API.
theme: just-the-docs

url: https://annimukherjee.github.io/ProKabaddi_API/

aux_links:
  API Repository: https://github.com/abhineetraj1/prokabaddiAPI/tree/main

plugins:
  - jekyll-default-layout