title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://annimukherjee.github.io/ProKabaddi_API/

aux_links:
  API Repository: https://github.com/abhineetraj1/prokabaddiAPI/tree/main
