site_name: ProKabaddi-API Documentation
nav:
  - Home: index_hello.md
  - Team: about.md
  - Player: index_playerfns.md
  - Future Work: index_plannedfeats.md

theme: 
  name: mkdocs
  locale: en
  use_directory_urls: false
  user_color_mode_toggle: true
  
  extra:
    version: 1.0

