title: kabaddiPy
description: A comprehensive description of all the functions provided by the API.
theme: just-the-docs

baseurl: "/docs"

url: https://github.com/kabaddiPy/kabaddiPy

aux_links:
  API Repository: https://github.com/kabaddiPy/kabaddiPy

nav_enabled: true

#logo: "/assets/kabaddi_api_logo.png"
#favicon_ico: "/assets/favicon.ico"
favicon_ico: "/assets/images/favicon.ico"




search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

heading_anchors: true


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
# color_scheme: "dark"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
enable_copy_code_button: true


#permalink: pretty

nav_external_links:
  - title: ProKabaddi Official Website
    url: https://www.prokabaddi.com/stats
    
  # - title: Kabaddi Adda
  #   url: https://www.kabaddiadda.com/players


footer_content: "Distributed by an <a href=\"https://github.com/kabaddiPy/kabaddiPy/tree/main?tab=GPL-2.0-1-ov-file\">GPL license.</a>"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"


callouts_level: quiet # or loud

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


#kramdown:
#  syntax_highlighter_opts:
#    block:
#      line_numbers: true
