title: Documentation for the ProKabaddi API
description: A comprehensive description of all the endpoints for the API.
theme: just-the-docs

baseurl: "/docs"

url: https://annimukherjee.github.io/ProKabaddi_API/

aux_links:
  API Repository: https://github.com/abhineetraj1/prokabaddiAPI/tree/main


nav_enabled: true


heading_anchors: true


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
# color_scheme: "dark"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# For copy button on code
enable_copy_code_button: true

search_enabled: true

# permalink: pretty

nav_external_links:
  - title: ProKabaddi Official Website
    url: https://www.prokabaddi.com/stats
  - title: Kabaddi Adda
    url: https://www.kabaddiadda.com/players
